AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tp2 manual
Resources:
  Productos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        ListEnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CreateEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        UpdateDelivered:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put